//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsManagement.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SongsManagementEntities : DbContext
    {
        public SongsManagementEntities()
            : base("name=SongsManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_LoginInfo> User_LoginInfo { get; set; }
        public virtual DbSet<User_PersonalInfo> User_PersonalInfo { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
    }
}
