//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_LoginInfo
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> LoginAttempts { get; set; }
        public Nullable<System.Guid> UserTypeId { get; set; }
        public Nullable<System.DateTime> CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
